### ISSUE TITLE
你好,我下载使用之后,首页访问正常,但是登录一直说找不到页面.请问这个问题怎么解决.非常感谢!如果方便的话请加我QQ394739578谢谢

### ISSUE THREAD

**Issue by uncleSh** [stevennight/Stevennight_Live#5]

**Comment by stevennight** [comment]
因为之前弄的时候是做了另外一个东西用于登录的，不知道是否使用了呢？
https://github.com/stevennight/Stevennight_Account_Center
现在看来好像有点多余（笑...
