### ISSUE TITLE
啊哈哈哈兄弟真是巧啊

### ISSUE THREAD

**Issue by KirosHan** [stevennight/Stevennight_Live#6]
我当时也做了一个同样功能的web，好怀念

**Comment by stevennight** [comment]
烂代码见笑了（😀
我这算是自娱自乐的东西吧。

**Comment by KirosHan** [comment]
我当时在学校局域网用的    也是烂代码    本来用得Flash Media Server   后来还改了一版用七牛云的服务器
哈哈   只是搜别的恰好搜到你的project    好怀念
